### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TheNimbleNinja** [ChloeDawn/BeaconOverhaul#10]
**Describe the bug**
crash on startup

**Reproduction steps**
-add od

**Expected behavior**
crash on startup

**Screenshots**
none

**Environment (please complete the following information):**
 - Minecraft version: 1.17
 - Loader version [e.g. 0.11.3 fabric
 - Mod version Beacon Overhaul 1.4.0+1.17

**Additional context**
https://gist.github.com/TheNimbleNinja/2faecc7be63eff77c29376049bc0fc95

**Comment by ChloeDawn** [comment]
This is an incompatibility with https://github.com/JamiesWhiteShirt/reach-entity-attributes, not Beacon Overhaul. One of the mods in your pack is modifying reach distance itself, which conflicts with our universal library.

**Comment by ChloeDawn** [comment]
Actually, if you can run the game with the following Java argument **`-Dmixin.dumpTargetOnFailure=true`**, it will provide us with the information we need. You can add this to your MultiMC instance under `Edit Instance -> Settings -> Java arguments`

**Comment by ChloeDawn** [comment]
I have reported the conflict to the author of the conflicting mod, LotTweaks. Until this is resolved the solution is to remove that mod from your pack. https://www.curseforge.com/minecraft/mc-mods/lottweaks#c53
