### ISSUE TITLE
Beacon flight

### ISSUE THREAD

**Issue by Slomaxonical-907** [ChloeDawn/BeaconOverhaul#12]
I'm not finding fabric beacon flight mods for 1.17. I'm sure a lot of people would appreciate the addition, it could replace slow falling or even be turned off in a config.
It would be nice to have that in the mod to avoid incompatibilities (in case of other mods add it). 
That's all i have to say. Thanks for the great mod.

**Comment by ChloeDawn** [comment]
I have no intention of adding a creative flight to beacons, sorry. This mod focuses heavily on balanced design, and there's no simple way to balance something as powerful as that. Even if I were to disable it by default, optional content is still content, and it wouldn't sit well with me to provide such a powerful mechanic within the mod when everything else has had the time and thought put into it to make it feel fair and well rounded.

For flight in vanilla survival, I recommend using the elytra paired with fireworks.
