### ISSUE TITLE
More control and configuration

### ISSUE THREAD

**Issue by SylisMC** [ChloeDawn/BeaconOverhaul#13]
### **What lead me to this idea**
I am working on a modpack revolving around a data pack im developing that shrinks the player to be half-sized, effectively changing how the game is played from the ground up, without a complicated learning curve. the world is the same after all. youre just half sized.

A HUGE aspect of this pack is that players are forced to travel the world taking terrain into account, after all, they are only 1 block tall... every step is a jump, every jump is a cliff. this presents the problem of building. one of the greatest hurdles for the player will be building. as they can only jump 1/2 a block high.

Using your wonderful mod, I am repurposing the hunger effect to additionally restore the player to full size and wanted to also add an option to allow the player to fly. I've explored the possibility of using flying rings and enchantments. flying is a really hard feature to balance. And so, I was going to allow the player to fly via beacon. one small restricted location.

So, I Can (and probably will) end up using the same method i use to grow the player via hunger, but it was a lot of work. and its not 100% reliable. not to mention it forces me to trigger removed and adding effects from players constantly. creating additional lag for no good reason. 

### **Idea**
And that's where I was thinking... wouldn't it be nice if the beacon overhaul mod just let me overhaul beacons... as i see fit? Not all players play the same way. and for that reason, options are always nice. they allow players to craft an experience exactly the way they want it

 
### **Concept**
instead of BeaconOverhaul Adding existing Minecraft features (and 2 new ones) why not add two effect slots to the beacon that can be configured (set to your effects by default) Now a player can download other popular mods like charm and set the beacon to give charm:spelunking. or climbing from the bewitchment mod or in my case, fly from FlightBeacons

By doing so, you give modpack makers the freedom to really take control of beacons and create the perfect beacon experience, By default, nothing would change... but under the hood, youd place a LOT more power in the hands of the user (and then stubborn guys like me don't have to spend 10 hours creating a modpack to replicate this feature, lol)

**Comment by ChloeDawn** [comment]
I appreciate the time you put into writing up this suggestion, however, I, unfortunately, do not feel comfortable making such changes. Introducing such an open configuration for users would require me to fundamentally change the entire mod as it currently stands, and doing so would undo all of the thought and care that has been put into the design and balance of it. I apologise if the name of the mod was misleading, but the intention was never to make beacons more configurable, it was to expand them in a fashion that still felt like vanilla. What you're asking for is a completely different mod concept, and I would recommend looking for other solutions to your problem or commissioning a developer to create such a mod for you. I wish you luck in your endeavours.
