### ISSUE TITLE
[Feature Request] effects settings

### ISSUE THREAD

**Issue by elhertz** [ChloeDawn/BeaconOverhaul#15]
I just want to reduce the reach of "long reach" cause i think it's too broken right now

**Comment by ChloeDawn** [comment]
I had been considering reducing the reach distance of the effect, as I agree, it feels a little too powerful. What do you think would be a good step in reach distance per level of effect?

**Comment by elhertz** [comment]
I don't know if this is possible but it'd be nice to have an option to choose between block reach, pvp reach, and both. I don't mind using  the effect for building but it feels to OP when pvping-pveing.
I don't really know what to answer to your question. I tend to play more seriously and I love little additions but I don't like when something is too OP, so a way to set our own settings would be awesome.

**Comment by milkev** [comment]
i think a config for players to set their own values would be a great idea.

block reach and attack reach will almost always be op in pvp/pve even if its just a one block increase. personally i think the mere fact that its a beacon effect, being limitted both to the vanilla endgame and only certain areas of the world is already enough of a downside to make it fair, but thats just an opinion :p

**Comment by elhertz** [comment]
> i think a config for players to set their own values would be a great idea.
> 
> block reach and attack reach will almost always be op in pvp/pve even if its just a one block increase. personally i think the mere fact that its a beacon effect, being limitted both to the vanilla endgame and only certain areas of the world is already enough of a downside to make it fair, but thats just an opinion :p

Yeah, it kinda depends on the theme of your server tho. I wouldn't like my players farming bosses from a safe distance even if it's endgame. As you said, a config for players to set their own values would be* nice.

**Comment by ChloeDawn** [comment]
I will introduce an integer game rule for defining the reach increment per effect level. Block reach and attack range will share the same game rule as I feel it would be counter-intuitive if the player were able to reach entities further than they did blocks or vice versa.

**Comment by elhertz** [comment]
Nice!

**Comment by ChloeDawn** [comment]
Implemented in https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.4.2+1.17 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3476553
