### ISSUE TITLE
Effects Issue

### ISSUE THREAD

**Issue by GmoneyRL** [ChloeDawn/BeaconOverhaul#22]
I can't seem to get the effects to show up on my beacon on 1.18.2. Idk if im doing something wrong

**Comment by ChloeDawn** [comment]
Do you have the mod installed on both the client and the server?

**Comment by GmoneyRL** [comment]
Yes I do

**Comment by ChloeDawn** [comment]
Please provide a mods list and the version of the mod you are using

**Comment by GmoneyRL** [comment]
[modlist.zip](https://github.com/ChloeDawn/BeaconOverhaul/files/8587242/modlist.zip)
https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3683935

**Comment by ChloeDawn** [comment]
Beacon Overhaul is a Fabric mod, it will not run on Forge
