### ISSUE TITLE
Long Reach doesn't work

### ISSUE THREAD

**Issue by unificat** [ChloeDawn/BeaconOverhaul#23]
**Describe the bug**
The Long Reach effect applies and shows up, but nothing is actually done to the reach.

**Reproduction steps**
1. place 1.18.1 mod into the mods folder
2. launch up Minecraft
3. load into the world
4. apply effect via beacon
5. boom doesn't work

**Expected behavior**
I just want long reach man

**Environment (please complete the following information):**
 - Minecraft version: 1.18.1
 - Loader version 0.14.5-1.18.1
 - Mod version 1.18.1

**Additional context**
I have a few other mods installed, but none of them have anything to do with beacons or effects,

**Comment by ChloeDawn** [comment]
Please provide your mod list, it may be a conflict. It is also worth noting that the default reach multiplier was reduced from 5 blocks to 2 blocks per potency level in [1.4.2+1.17](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3476553), however, it can be configured with a game rule if you wish it to be more significant, `longReachIncrement`.

**Comment by ChloeDawn** [comment]
The long-reach effect is still working correctly in the latest releases of Beacon Overhaul, if you are still experiencing this issue I will need more information about your instance. Ensure you are downloading Beacon Overhaul from official sources. The latest releases are **1.7.3+1.19.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.7.3+1.19.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983948) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.7.3+1.19.2) ] and **1.6.1+1.18.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.6.1+1.18.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983955) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.6.1+1.18.2) ]
