### ISSUE TITLE
Beacon of Higher tears (diamond, netherite) are not applying the correct level of  a effect

### ISSUE THREAD

**Issue by K0KE11** [ChloeDawn/BeaconOverhaul#35]
**Describe the bug**
In minecraft version 1.19 when you build a beacon of netherite of 4 steps and click in the Haste IV option it only gives you Haste III, the same for every effect. It seems to give you one level below the one it says it's going to give. I thought the issue was that the extra option doesn't work but they do. It just seem the cap is level 3 for effects.

**Reproduction steps**
Build a beacon of 4 steps with netherite blocks, then click in the desire effect (In my case Haste or Long Reach) and then click in the extra option of a 4 step piramid which in the netherite beacon it will say Haste IV or Long Reach IV) it will only give u a level 3 effect.

**Expected behavior**
It supposed to give level 4 effects or the level the tag says it's going to give.

**Environment (please complete the following information):**
 - Minecraft version: [1.19]
 - Loader version [fabric 0.14]
 - Mod version [1.7.1]

**Screenshots**
![2023-07-27_19 49 15](https://github.com/ChloeDawn/BeaconOverhaul/assets/81993061/f19b0d24-bdb0-4d9c-8e92-cd862acbd113)
![2023-07-27_19 51 25](https://github.com/ChloeDawn/BeaconOverhaul/assets/81993061/6090c2d9-fbc7-4a47-bc59-8cdf359b6933)

**Comment by ChloeDawn** [comment]
Unable to reproduce, please make sure you are on the latest version of the mod
