### ISSUE TITLE
1.19.4 no pigs (weird, i know)

### ISSUE THREAD

**Issue by blu12335** [ChloeDawn/BeaconOverhaul#39]
for some reason the 1.19.4 fabric version causes pigs to never spawn...cant spawn with commands or the spawn egg, was wondering why my world didnt ever have pigs and after testings i figured it was this mod......took forever having to open and close the game lol, but ya last test i did was make a new instance and only had this mod and the fabric api in it...same result...no pigs.....ive opened the jar and tried finding anything related to pigs and nothing and idk how to open class files in a readable way so idk about that..........still confused on how a beacon mod will cause no pigs........basically the beacon mod wanted the bacon to begone....

**Comment by ChloeDawn** [comment]
Fixed in [1.7.7+1.19.4](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.7.7%2B1.19.4) ([CurseForge](https://curseforge.com/minecraft/mc-mods/beaconoverhaul/files/4715715), [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.7.7+1.19.4))
