### ISSUE TITLE
(1.16) Beacon Overhaul Breaks Horse Step Assist

### ISSUE THREAD

**Issue by DarianLStephens** [ChloeDawn/BeaconOverhaul#4]
With this mod installed, horses need to jump in order to climb up a single block.
After removing this mod, horse behaviour returns to normal.

**Reproduction steps**
1. Install mod
2. Ride horse
3. Try to walk up a block

**Expected behavior**
That horse step assist is unaffected.

**Screenshots**
Screenshots don't really do anything to help.

**Environment (please complete the following information):**
 - Minecraft version: [1.16.4]
 - Loader version [0.11.1]
 - Mod version [1.1.0]

**Comment by ChloeDawn** [comment]
Fixed in:

https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.2.0+1.17 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3183554
https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.2.0+1.16 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3183556
