### ISSUE TITLE
Pehkui conflicts with the reach-entity-attributes library

### ISSUE THREAD

**Issue by DarianLStephens** [ChloeDawn/BeaconOverhaul#6]
**Describe the bug**
When you install both Beacon Overhaul and Pehkui, the game will crash when loading.

**Reproduction steps**
1. Add Pehkui
2. Add Beacon Overhaul
3. Launch the game
4. Crash while launching

**Expected behavior**
To not crash.

**Environment (please complete the following information):**
 - Minecraft version: [1.16.5]
 - Loader version [0.11.2]
 - Mod version [1.3.0]

**Additional context**
Pastebin link to the crash log:
https://pastebin.com/89ugWGqL

**Comment by InsaanNotFound** [comment]
This, having same issue, here is my log https://pastebin.com/yGa6mUek

**Comment by ChloeDawn** [comment]
This is a conflict that needs to be resolved on Pehkui's end. They should be using the [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) library for alterations to player reach distance, as the necessary changes are integral and not compatible with mixin overlap (hence this crash).

**Comment by ChloeDawn** [comment]
On second thought, I will keep this issue open until the conflict is resolved.

**Comment by ChloeDawn** [comment]
Fixed in https://github.com/Virtuoel/Pehkui/releases/tag/1.8.0 https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3223971
