### ISSUE TITLE
Interactible Objects 'Close' When Far

### ISSUE THREAD

**Issue by DarianLStephens** [ChloeDawn/BeaconOverhaul#7]
**Describe the bug**
If you place something like a Barrel and try to interact with it from more than a few blocks away (Within the vanilla interaction distance, as well), the Barrel will immediately close in-world, though the GUI remains open.

**Reproduction steps**
1. Place a barrel
2. Step a few blocks away from said barrel
3. Open the barrel
4. Hear the open and close sound play at the same time, and the barrel's opening immediately closes.

**Expected behavior**
For the barrel to stay open while you've got the GUI open.

**Screenshots**

**Environment (please complete the following information):**
 - Minecraft version: [1.16.5]
 - Loader version [0.11.2]
 - Mod version [1.3.0]

**Additional context**
I disabled some other mods also affecting reach before discovering this one had the issue. This included Pehkui, which didn't end up affecting anything.

**Comment by ChloeDawn** [comment]
https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues/9

**Comment by ChloeDawn** [comment]
Fixed in:

https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.3.1+1.16 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3240614
https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.3.1+1.17 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3240624
