### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by DeeChael** [ChloeDawn/BeaconOverhaul#8]
Even though there are only 2 words in the language file, I still made a Chinese translation
Because github cannot upload json file, I put it in a zip file
[The translation file](https://github.com/ChloeDawn/BeaconOverhaul/files/6446698/zh_cn.zip)

**Comment by ChloeDawn** [comment]
Implemented in https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.4.0+1.17 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3350334
